#!../../bin/linux-x86_64/CTRL-SUP
#+======================================================================
# $HeadURL: https://svnpub.iter.org/codac/iter/codac/dev/units/m-epics-iter-templates/trunk/templates/genericBoot/ioc/st.cmd $
# $Id: st.cmd 58139 2015-07-09 11:55:11Z zagara $
#
# Project       : CODAC Core System
#
# Description   : ITER ioc template EPICS start up file
#
# Author(s)     : This file was generated by CODAC development toolkit
#
# Copyright (c) : 2010-2018 ITER Organization,
#                 CS 90 046
#                 13067 St. Paul-lez-Durance Cedex
#                 France
#
# This file is part of ITER CODAC software.
# For the terms and conditions of redistribution or use of this software
# refer to the file ITER-LICENSE.TXT located in the top level directory
# of the distribution package.
#
#-======================================================================

< envPaths
< envSystem
< envUser

cd "${TOP}"

#############################################
## Register all support components         ##
#############################################

dbLoadDatabase "dbd/CTRL-SUP.dbd"
CTRL_SUP_registerRecordDeviceDriver pdbbase

< "${TOP}/iocBoot/iocCTRL-SUP-PSH0SYSM/sddPreDriverConf.cmd"
< "${TOP}/iocBoot/iocCTRL-SUP-PSH0SYSM/userPreDriverConf.cmd"
< "${TOP}/iocBoot/iocCTRL-SUP-PSH0SYSM/threadSchedulingConf.cmd"
< "${TOP}/iocBoot/iocCTRL-SUP-PSH0SYSM/dbToLoad.cmd"
< "${TOP}/iocBoot/iocCTRL-SUP-PSH0SYSM/iocCTRL-SUP-PSH0SYSM-preSaveRestore.cmd"

#############################################
## IOC Logging                             ##
#############################################
iocLogInit
iocLogPrefix "${STY} : "

#############################################
## IOC initialization                      ##
#############################################
cd "${TOP}/db"
iocInit

< "${TOP}/iocBoot/iocCTRL-SUP-PSH0SYSM/iocCTRL-SUP-PSH0SYSM-postSaveRestore.cmd"
< "${TOP}/iocBoot/iocCTRL-SUP-PSH0SYSM/sddSeqToLoad.cmd"
< "${TOP}/iocBoot/iocCTRL-SUP-PSH0SYSM/seqToLoad.cmd"
< "${TOP}/iocBoot/iocCTRL-SUP-PSH0SYSM/sddPostDriverConf.cmd"
< "${TOP}/iocBoot/iocCTRL-SUP-PSH0SYSM/userPostDriverConf.cmd"


dbl > "${CODAC_VAR}/iocdump/${UNIT_NAME}/${IOC_NAME}-${IOC_BOOT_TIME}.dbl"
dbior > "${CODAC_VAR}/iocdump/${UNIT_NAME}/${IOC_NAME}-${IOC_BOOT_TIME}.dbior"
dbhcr > "${CODAC_VAR}/iocdump/${UNIT_NAME}/${IOC_NAME}-${IOC_BOOT_TIME}.dbhcr"

