<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<databrowser>
    <title>Tank Level </title>
    <save_changes>true</save_changes>
    <show_legend>true</show_legend>
    <show_toolbar>true</show_toolbar>
    <grid>true</grid>
    <scroll>true</scroll>
    <update_period>3.0</update_period>
    <scroll_step>5</scroll_step>
    <start>-10.08 min</start>
    <end>now</end>
    <archive_rescale>NONE</archive_rescale>
    <background>
        <red>229</red>
        <green>229</green>
        <blue>229</blue>
    </background>
    <title_font>DejaVu Sans Mono|26|0</title_font>
    <label_font>DejaVu Sans Mono|20|0</label_font>
    <scale_font>DejaVu Sans Mono|20|0</scale_font>
    <legend_font>DejaVu Sans Mono|20|0</legend_font>
    <axes>
        <axis>
            <visible>true</visible>
            <name>m3</name>
            <use_axis_name>true</use_axis_name>
            <use_trace_names>false</use_trace_names>
            <right>false</right>
            <color>
                <red>77</red>
                <green>77</green>
                <blue>77</blue>
            </color>
            <label_font>|10|1</label_font>
            <scale_font>DejaVu Sans Mono|20|0</scale_font>
            <min>0.0</min>
            <max>100.0</max>
            <grid>false</grid>
            <autoscale>false</autoscale>
            <log_scale>false</log_scale>
        </axis>
        <axis>
            <visible>false</visible>
            <name>TEST-BST0:TANK-LEVEL.LOW</name>
            <use_axis_name>false</use_axis_name>
            <use_trace_names>false</use_trace_names>
            <right>false</right>
            <color>
                <red>242</red>
                <green>26</green>
                <blue>26</blue>
            </color>
            <label_font>|10|1</label_font>
            <scale_font>DejaVu Sans Mono|20|0</scale_font>
            <min>0.0</min>
            <max>100.0</max>
            <grid>false</grid>
            <autoscale>false</autoscale>
            <log_scale>false</log_scale>
        </axis>
        <axis>
            <visible>false</visible>
            <name>TEST-BST0:TANK-LEVEL.HIGH</name>
            <use_axis_name>false</use_axis_name>
            <use_trace_names>false</use_trace_names>
            <right>false</right>
            <color>
                <red>33</red>
                <green>179</green>
                <blue>33</blue>
            </color>
            <label_font>|10|1</label_font>
            <scale_font>DejaVu Sans Mono|20|0</scale_font>
            <min>0.0</min>
            <max>100.0</max>
            <grid>false</grid>
            <autoscale>false</autoscale>
            <log_scale>false</log_scale>
        </axis>
    </axes>
    <annotations>
    </annotations>
    <pvlist>
        <pv>
            <display_name>TEST-BST0:TANK-LEVEL</display_name>
            <visible>true</visible>
            <name>TEST-BST0:TANK-LEVEL</name>
            <axis>0</axis>
            <color>
                <red>21</red>
                <green>21</green>
                <blue>196</blue>
            </color>
            <trace_type>AREA</trace_type>
            <linewidth>2</linewidth>
            <point_type>NONE</point_type>
            <point_size>2</point_size>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>Archive RDB</name>
                <url>jdbc:postgresql://localhost/css_archive_3_0_0</url>
                <key>1</key>
            </archive>
        </pv>
        <pv>
            <display_name>TEST-BST0:TANK-LEVEL.LOW</display_name>
            <visible>true</visible>
            <name>TEST-BST0:TANK-LEVEL.LOW</name>
            <axis>0</axis>
            <color>
                <red>242</red>
                <green>26</green>
                <blue>26</blue>
            </color>
            <trace_type>AREA</trace_type>
            <linewidth>2</linewidth>
            <point_type>NONE</point_type>
            <point_size>2</point_size>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>Archive RDB</name>
                <url>jdbc:postgresql://localhost/css_archive_3_0_0</url>
                <key>1</key>
            </archive>
        </pv>
        <pv>
            <display_name>TEST-BST0:TANK-LEVEL.HIGH</display_name>
            <visible>true</visible>
            <name>TEST-BST0:TANK-LEVEL.HIGH</name>
            <axis>0</axis>
            <color>
                <red>255</red>
                <green>165</green>
                <blue>0</blue>
            </color>
            <trace_type>AREA</trace_type>
            <linewidth>2</linewidth>
            <point_type>NONE</point_type>
            <point_size>2</point_size>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>Archive RDB</name>
                <url>jdbc:postgresql://localhost/css_archive_3_0_0</url>
                <key>1</key>
            </archive>
        </pv>
    </pvlist>
</databrowser>